services:
  db:
    image: postgres
    container_name: db
    volumes:
      - "pg_data:/var/lib/postgresql/data"
    env_file:
      - .env
    ports:
      - "5432:5432"

  auth:
    container_name: auth_service
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - db


volumes:
  pg_data: