app:
  name: "Auth service"

network:
  host: "0.0.0.0"
  port: "8081"

postgres:
  user: "auth_service"
  password: "12345"
  host: "db"
  port: "5432"
  database: "auth"

tokens:
  accessTTL: "10m"
  # refreshTTL: "30s"
  refreshTTL: "43200m"
